spring:
  datasource:
    main:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.28.16:3306/test
      username: root
      password: root
      #type: com.alibaba.druid.pool.DruidDataSource
    shard:
      url-0: jdbc:mysql://192.168.28.16:3306/test_0
      url-1: jdbc:mysql://192.168.28.16:3306/test_1
      username: root
      password: root
      initial-size: 3
      min-idle: 3
      max-active: 100

      #druid
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#
#      filters: stat,wall,log4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
  elasticsearch:
    rest:
      uris: 192.168.28.16:9200
  redis:
    host: 192.168.28.16
    port: 6379

rocketmq:
  name-server: 192.168.28.16:9876 # 访问地址
  producer:
    group: Pro_Group # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
